---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages

clone:
  depth: 2

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install
    image: node
    pull: if-not-exists
    commands:
      - yarn

  - name: build
    image: node:14
    commands:
      - yarn build-all

  - name: publish-site
    failure: ignore
    image: plugins/gh-pages
    settings:
      pages_directory: public/
      username:
        from_secret: github_token
      password: x-oauth-basic
    when:
      branch:
        - main
      event:
        exclude:
          - pull-request

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /cache
