---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages

clone:
  depth: 2

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install
    image: node
    pull: if-not-exists
    commands:
      - yarn

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  - name: test
    image: node
    commands:
      - yarn check-types
      - yarn lint
      - yarn test

  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov-token
      paths:
        - coverage

  - name: build
    image: node:14
    commands:
      - yarn fake
      - yarn build

volumes:
  - name: cache
    host:
      path: /cache
