---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages

clone:
  depth: 2

steps:
  - name: install
    image: node:16
    commands:
      - yarn --immutable

  - name: test
    image: node:16
    commands:
      - yarn check-types
      - yarn lint
      - yarn test

  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov-token
      paths:
        - coverage
    when:
      status:
        - success
        - failure

  - name: build
    image: node:16
    commands:
      - yarn fake
      - yarn build
