import { writeCoverLetter, writeResume } from "./src/helpers/createFakeData";

/* Run this file to set up or reset the project.
 * I like to use `bun -b setup.ts` but `node-ts setup.ts` should work too.
 *
 * WARNING! This is destructive. These scripts overwrite any existing files. */

/* This creates `src/data/data.json` with details generated by faker */
writeResume();

/* This creates `src/data/letter.md` with some lorem ipsum */
writeCoverLetter();
